namedValues:
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"
  - name: environment
    properties:
      displayName: environment
      value: "development1"
  - name: tifsecret1
    properties:
      displayName: tifsecret1
      keyVault:
       secretIdentifier: "https://feiaz-apim-test.vault.azure.net/secrets/tifsecret1"
      secret: true
  - name: tifsecret2
    properties:
      displayName: tifsecret2
      keyVault:
       secretIdentifier: "https://feiaz-apim-test.vault.azure.net/secrets/tifsecret2"
      secret: true      
apis:
 - name: api
   properties:
    path: testdev1
    apiRevision: '1'
    authenticationSettings: {}
    description: 'hello there'
    displayName: hellothereindev
    format:  openapi+json-link	
    value: https://petstore3.swagger.io/api/v3/openapi.json
    
backends:
 - name: backend2
   properties:
    url: "https://www.cnn.com"
    type: Single
    tls:
     validateCertificateChain: true
     validateCertificateName: true
    credentials:
     certificate: ["74CF3A4A8209C62C478FBAD9C1FB3012A844D9A1"]
     certificateIds: ["/subscriptions/db73da55-ad6a-4d59-aeea-bba62c278f2a/resourceGroups/apim/providers/Microsoft.ApiManagement/service/feiaz-apim-test/certificates/testcert"]